image: docker:19.03.8

services:
  - docker:19.03.8-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
test:
  stage: test
  script:
    - "docker build -t registry.gitlab.com/nishranjan/bpcl/client/test:latest -f ./client/Dockerfile.dev ./client"
    - "docker run -e CI=true registry.gitlab.com/nishranjan/bpcl/client/test:latest npm run test -- --coverage"
  tags:
    - my-runner

build:
  stage: build
  script:
    # - "docker build -t registry.gitlab.com/nishranjan/bpcl/client:latest ./client"
    - "docker build -t registry.gitlab.com/nishranjan/bpcl/server:latest -f ./server/Dockerfile.dev ./server"
    - "docker build -t registry.gitlab.com/nishranjan/bpcl/server:nginxreverseproxy ./server"
    # - "docker push registry.gitlab.com/nishranjan/bpcl/client:latest"
    - "docker push registry.gitlab.com/nishranjan/bpcl/server:latest"
    - "docker push registry.gitlab.com/nishranjan/bpcl/server:nginxreverseproxy"
  only:
    - master
  tags:
    - my-runner
deploy:
  stage: deploy
  script:
    - docker run -d -p 80:80 registry.gitlab.com/nishranjan/bpcl/client:latest
    - docker run -d -p 5000:5000 registry.gitlab.com/nishranjan/bpcl/server:latest
  tags:
    - my-runner
